import {makeStyles} from '@material-ui/core/styles'

const useClasses = makeStyles(theme =>({
    modalContainer:{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
        width: '100%',
        height: '100%',
    },
    ilustratieLogin:{
        width: '90%',
        // marginBottom: '30px',
        // marginTop: '15px',
        margin:'0 auto',
    },
    inputLogin:{
        '& label':{
            // paddingLeft: '55px',
            fontWeight: 800,
        },
        '& input':{
            paddingLeft: '10px',
        },
        '& root':{
            backgroundColor: 'red',
        },
        '& label.Mui-focused':{
            color:'#f35',
            
        },
        '& .MuiInput-underline:after': {
            borderBottomColor: '#f35',
          },
        margin:'0 auto',
        width: 'calc(100% - 30px)',
        fontWeight: 800,
        marginTop: '15px',
        // backgroundColor: '#efefef',
    },
    modalTitle:{
        '& span':{
            color:'#f35',
        },
        // marginBottom:'15px',
        marginTop: '15px',
        margin:'0 auto',
        fontSize: '17pt',
        fontWeight: 900,
    },
    loginButton:{
        '& root':{
            backgroundColor: '#f35 !important',
        },
        marginTop: '15px',
        backgroundColor: '#f35 !important',
        color:'white',
        fontSize: '8.5pt',
        fontWeight: 900,
        width: 'calc(100% - 30px)',
        padding: '5px',
        height: '35px',
        margin:'0 auto',
        marginTop: '25px',
    },
    bottomInfo:{
        margin: '0 auto',
        marginTop: 'auto',
        '& p':{
            textAlign:'center',
            marginTop: '10px',
            '& span':{
                fontWeight: 800,
                color:'#f35'
            }
        }
    },
    modalHeader:{
        display: 'flex',
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
      },
      modalAvatarInfo:{
        '& img':{
            marginRight: '10px',
            width: '64px',
            height: '64px',
            objectFit: 'cover',
            borderRadius: '50%',
            border:'2px solid #dbdbdb',
            boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
        },
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
      },
      modalInfoNume:{
        fontWeight: 900,
        fontSize: '13.5pt'
      },
      modalInfoLocatie:{
        marginTop: '3.4px',
        fontWeight: 800,
        fontSize: '8pt',
        fontStyle: 'italic',
        textTransform: 'uppercase',
      },
      priceCategory:{
          width: '100%',
          display: 'flex',
          flexDirection: 'row',
          marginTop: '15px',
          borderRadius: '4px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
      },
      modalPret:{
        display: 'flex',
        alignItems: 'center',
        backgroundColor: '#f35',
        padding: '8px 10px 8px 10px',
        fontSize: '15pt',
        fontWeight: 900,
        color: 'white',
        borderTopLeftRadius: '4px',
        borderBottomLeftRadius: '4px',
        border: '0 !important'
      },
      modalCategorie:{
          display: 'flex',
          alignItems: 'center',
          paddingLeft: '10px',
          backgroundColor: '#262626',
          width: '100%',
          borderTopRightRadius: '4px',
          borderBottomRightRadius: '4px',
          color:'#fff',
          fontSize: '9pt',
          fontWeight: 800,
          border: '0 !important'
      },
      modalAttributes:{
          display: 'flex',
          marginTop: '15px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
          borderRadius: '4px',
          width: '100%',
      },
      modalAttributeTitle:{
          '& :first-of-type':{
                backgroundColor: 'black',
          },
        display: 'flex',
        alignItems: 'center',
        backgroundColor: '#efefef',
        padding: '8px 10px 8px 10px',
        fontSize: '11pt',
        fontWeight: 900,
        color: '#262626',
        // borderTopLeftRadius: '4px',
        // borderBottomLeftRadius: '4px',
        border: '0 !important'
      },
      borderBottom:{
        borderBottom: '1px solid rgba(42,42,43,.2)',
      },
      modalAttributeText:{
        '& :first-of-type':{
          
          background: 'white !important',
        },
        background: 'white !important',
        display: 'flex',
        alignItems: 'center',
        padding: '0px 10px 0px 10px',
        fontSize: '10pt',
        fontWeight: 900,
        color: '#262626',
        // border: '0 !important',
        width: '100%',
        height: '50%',
      },
      modalImagesContainer:{
        marginTop: '15px',
        width: '100%',
        height: '125px',
      },
      modalImages:{
          '& img':{
            height: '100%',
            width: '220px',
            minWidth: '220px',
            maxWidth: '220px',
            objectFit: 'cover',
            marginRight: '15px',
            borderRadius: '4px',
          },
          height: '100%',
          display: 'flex',
          flexDirection: 'row',
          overflowX: 'auto',
          width: 'auto',
          minWidth: '100%',
          minHeight: '100px',
          position: 'relative',
          scrollBehavior: 'smooth',
          position: 'relative',
      },
      anuntModalBadges:{
          top:'20px',
          right: '5px',
          width: '30px',
          height: '30px',
          backgroundColor: '#f35',
          borderRadius: '50%',
          fontWeight: 900,
          fontSize: '8pt',
      },
      modalTitluAnunt:{
          marginTop: '15px',
          fontSize: '11pt',
          fontWeight: '800'
      },
      modalTitluAnuntAdaugare:{
        marginTop: '15px',
        marginBottom: '15px',
        width: '100%',
        height: '30px',
        fontSize: '11pt',
        fontWeight: '800',
        background: '#efefef',
        borderRadius: '4px',
    },
      modalTitluDescriere:{
        marginTop: '15px',
        fontSize: '11pt',
        fontWeight: '700'
      },
      modalNrTelefon:{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          fontSize: '12.5pt',
          color:'white',
          borderRadius: '4px',
          fontWeight: 700,
          width: '100%',
          backgroundColor: '#f35',
          minHeight: '45px',
          letterSpacing: '.5px',
          marginTop: '15px',
          alignSelf: 'flex-end',
      },
      modalDescriereText:{
          marginTop: '15px',
          overflowY: 'auto',
        //   height: '300px',
          fontSize: '9.5pt',
          width: '100%',
          fontSize: '10.5pt',
          fontWeight: 600,
      },
      modalDescriereTextUpload:{
        marginTop: '15px',
          overflowY: 'auto',
        //   height: '300px',
          fontSize: '9.5pt',
          width: '100%',
          // boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
          borderRadius: '4px',
          // padding: '10px !important'
      },
      paddingDescriere:{
        padding: '10px !important',
      },
      titluAdaugaAnunt:{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        //   width: '100%',
          background: 'white',
          padding: '6px 15px',
          color: '#f35',
          margin: 'auto',
          border: '2px solid #f35',
          borderRadius: '8px',
          fontSize: '10pt',
          fontWeight: '900',
          textTransform: 'uppercase',
          boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)'
      },
      pretInput:{
          width: '75px',
          height: '100%',
          '& underline':{
            border:'none !important',
        },
          '& input':{
            
            color:'white',
            textAlign: 'center',
            fontWeight: '900',
            fontSize: '12pt',
            padding: '0px',
          },
      },
      titluInput:{
        width: '100%',
          height: '100%',
          color:'#262626',
          paddingLeft: '15px',
          marginBottom: '15px',
          '& input':{
            color:'#262626',
            textAlign: 'left',
            fontWeight: '900',
            fontSize: '10.5pt',
            padding: '0px',
            
          },
      },
      uploadAnuntImagine:{
        position: 'relative',
      },
      uploadAnuntIcon:{
        position: 'absolute',
        top: '0px',
        right: '15px',
        borderRadius: '0px',
        borderBottomLeftRadius: '4px',
        borderTopRightRadius: '4px',
        background: '#f35 !important',
        color: 'white',
        minHeight: '20px',
        minWidth: '20px',
        width: '20px',
        height: '20px',
        padding: '0',
        fontSize: '7pt',
        fontWeight: 900,
      },
      adaugaImagineButton:{
        position: 'absolute',
        bottom: '-5px',
        right: '-5px',
        minWidth: '35px',
        minHeight: '35px',
        width: '35px',
        height: '35px',
        background: '#f35 !important',
        borderRadius: '50%',
        fontSize: '15pt',
        fontWeight: 900,
        color: 'white',
        padding: '0',
        display: 'flex !important',
        justifyContent: 'center !important',
        alignItems: 'center !important',
      },
      adaugaImaginiBox:{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'row',
        overflowX: 'auto',
        overflowY: 'hidden',
        scrollBehavior: 'smooth',
      },
      uploadAnunturiContainer:{
        '& img':{
          height: '100%',
          width: '170px',
          objectFit: 'cover',
          marginRight: '15px',
          borderRadius: '4px',
        },
        display: 'flex',
        flexDirection: 'row',
        width: '100%',
        minHeight: '19%',
        position: 'relative',
        scrollBehavior: 'smooth',
        position: 'relative',
        padding: '5px',
        borderRadius: '4px',
        boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
      },
      noAnunturi:{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
      },
      plusFigureButton:{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        margin: '0px 7px',
        width: '20px',
        height: '20px',
        background: '#f35',
        borderRadius: '50%',
        fontSize: '9pt',
        fontWeight: 900,
        color: 'white',
      },
      descriereContainer:{
        position: 'absolute',
        width: 'calc(100% - 30px)',
        maxHeight: 'calc(100% - 30px)',
        height: '350px',
        // maxHeight: '400px',
        backgroundColor: '#efefef',
        borderRadius: '4px',
        boxShadow: theme.shadows[5],
        padding: '10px',
        // margin: '15px',
        color: '#f35',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%,-50%) !important',
      },
      descriereInput:{
        fontWeight: 700,
        fontSize: '11pt',
        color: '#262626',
        marginTop: '5px',
        width: '100%',
        padding: '10px',
        height: '100%',
        boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        background: 'white',
        borderRadius: '4px',
        overflowX: 'auto',
      },
      noDescriere:{
        width: 'calc(100% - 2px)',
        height: 'calc(100% - 2px)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        borderRadius: '4px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)'
        
      },
      noDescriereButton:{
        color:'white',
        fontWeight: 800,
        padding: '10px',
        textAlign: 'center',
        borderRadius: '4px',
        background: '#f35 !important',
        fontSize: '8pt',
      },
      firstLineTitle:{
        fontWeight: 900,
        fontSize: '8.5pt',
        color: '#262626',
      },
      secondLineText:{
        fontWeight: 700,
        fontSize: '8pt',
        color: '#262626',
        opacity: '.85',
        marginBottom: '15px',
      },
      uploadDescriereButoane:{
        width: '100%',
        height: '37px',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: '10px',
      },
      uploadDescriereButonCancel:{
        width: 'calc(50% - 5px)',
        height: '100%',

        // background: '#dbdbdb !important',
        // color: 'grey !important',
      },
      uploadDescriereButonOk:{
        width: 'calc(50% - 5px)',
        height: '30px',
        background: '#f35 !important',
        color:'white !important',
        fontWeight: 900,
        fontSize: '11pt',
        height: '100%'
      },
      h3Title:{
        display: 'flex',
        alignItems: 'center',
        width: '100%',
        justifyContent: 'center',
        fontSize: '13pt',
        fontWeight: 800,
        fontStyle: 'italic',
        // marginBottom: '5px',
        '& :first-child':{
          marginRight: '10px',
          height: '80%',
        }
      },
      iesiButon:{
        background: '#f35 !important',
        fontSize: '11pt',
        color: 'white',
        fontWeight: 800,
        padding: '10px 20px 10px 20px',
      },
      descriereP:{
        padding: '10px',
        fontSize: '11.5pt',
        fontWeight: 700,
        position: 'absolute',
        width: 'calc(100% - 20px)',
        height: '100%',
        wordBreak: 'break-word'
      },
      adaugaAnuntFooter:{
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        marginTop: '20px',
        minHeight: '35px',
        alignItems: 'center',
        justifyContent: 'center',
      },
      anuleazaButton:{
        width: 'calc(50% - 5px)',
        marginRight: '5px',
        height: '100%',
      },
      posteazaButton:{
        width: 'calc(50% - 5px)',
        marginLeft: '5px',
        height: '100%',
        background: '#f35 !important',
        color: 'white',
        fontWeight: 900,
      },
      telefonBox:{
        width: '100%',
        marginTop: '10px',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '9pt',
        fontWeight: 900,
      },
      telefon:{
        marginLeft: '15px',
        marginRight: '15px',
        fontSize: '12pt',
        color: '#f35',
      },
      modalTelefonAnunt:{
        background: '#f35',
        borderRadius: '4px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        '& input':{
          textAlign: 'center',
          color: 'white',
          width: '150px',
          fontSize: '10.5pt',
          paddingTop: '6px',
          paddingBottom: '6px',

        }
    },
    phoneIconUpload:{
      marginRight: '10px',
    },
    dialogModalMareTitle:{
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      fontSize: '13.5pt',
      fontWeight: 900,
      '& img':{
          marginRight: '15px',
      }
  },
  labelBox:{
    display: 'flex',
    alignItems: 'center',
  },
  errorBullet:{
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    background: '#f35',
    marginLeft: '5px',
    marginTop: '-2px',
  }
    }))

export default useClasses