export const SET_LOGIN_STATUS_LOADING = 'SET_LOGIN_STATUS_LOADING'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_IS_LOGGED = 'SET_IS_LOGGED'
export const RESET_LOGIN_ERRORS = 'RESET_LOGIN_ERRORS'
export const UPDATE_LOGIN_DATA = 'UPDATE_LOGIN_DATA'
export const RESET_LOGIN_REDUCER = 'RESET_LOGIN_REDUCER'

export const TRY_LOGIN = 'TRY_LOGIN'


///TEMPORARY REDUCER

export const CHANGE_MODAL_STATUS = 'CHANGE_MODAL_STATUS'
export const RESET_MODAL_STATUS = 'RESET_MODAL_STATUS'
export const RESET_TEMPORARY_REDUCER = 'RESET_TEMPORARY_REDUCER'


//ANUNTURI REDUCER

export const SET_ANUNTURI_LOADING = 'SET_ANUNTURI_LOADING'
export const SET_ANUNTURI = 'SET_ANUNTURI'


//SIGNUP REDUCER

export const SET_SIGNUP_STATUS_LOADING = 'SET_SIGNUP_STATUS_LOADING'
export const SET_SIGNUP_ERROR = 'SET_SIGNUP_ERROR'
export const RESET_SIGNUP_ERRORS = 'RESET_SIGNUP_ERRORS'
export const UPDATE_SIGNUP_DATA = 'UPDATE_SIGNUP_DATA'
export const RESET_SIGNUP_REDUCER = 'RESET_SIGNUP_REDUCER'